site_name: WebRTC
docs_dir: ./docs
nav:
  - Home: index.md
  - Web RTC:
    - Implementation: ./webrtc/imp.md
    - Calls Client: ./webrtc/callsclient.md
  - Cloudflare Calls: 
    - Cloudflare: ./cloudflarecalls/cloudflare.md
    - Calls: ./cloudflarecalls/calls.md
theme: readthedocs